---
- name: install pacman packages
  become: yes
  become_user: root
  command: "pacman -Sq --noconfirm {{ item }}"
  loop: "{{ packages }}"
  when: package_manager == 'pacman'

- name: install yay packages
  # TODO: this is nasty and again makes assumptions about bashrc having ssh keys loaded.
  command: "su -s /bin/bash -l {{ user }} -c 'yay -Sq --noconfirm --nodiffmenu --noeditmenu --nopgpfetch {{ item }}'"
  ignore_errors: yes
  loop: "{{ packages }}"
  when: package_manager == 'yay'
