---
- name: "Create root user ssh key"
  ansible.builtin.user:
    name: "root"
    password: "{{ password | password_hash('sha512') }}"
    shell: /bin/bash
    generate_ssh_key: true
    ssh_key_type: "ed25519"
    ssh_key_file: "/root/.ssh/id_ed25519"
    ssh_key_passphrase: "{{ ssh_key_passphrase }}"
  when: user == "root"

- name: "Create user {{ user }} with ssh key"
  ansible.builtin.user:
    name: "{{ user }}"
    password: "{{ password | password_hash('sha512') }}"
    # on_create: true
    shell: "{{ shell }}"
    groups: "{{ user_groups }}"
    create_home: true
    generate_ssh_key: true
    ssh_key_type: "ed25519"
    ssh_key_file: "/home/{{ user }}/.ssh/id_ed25519"
    ssh_key_passphrase: "{{ ssh_key_passphrase }}"
  when: user != "root"

# TODO: This is pretty disgusting. Also, we can't assume bashrc is used.
# Should try forwarding ssh agent instead.
- name: "{{ user }} bashrc"
  ansible.builtin.template:
    src: templates/bashrc.j2
    dest: "/home/{{ user }}/.bashrc"
    owner: "{{ user }}"
    mode: '0644'
  when: user != "root"

