---
- name: add root ssh key to GitHub
  # Fails if key has already been added to GitHub.
  ignore_errors: yes
  environment:
    GITHUB_TOKEN: "{{ github_token }}"
  command: gh ssh-key add /root/.ssh/id_ed25519.pub --title "ansible-root"
  when: user == 'root'

- name: add {{ user }} ssh key to GitHub
  # Fails if key has already been added to GitHub.
  ignore_errors: yes
  environment:
    GITHUB_TOKEN: "{{ github_token }}"
  command: "gh ssh-key add /home/{{ user }}/.ssh/id_ed25519.pub --title 'ansible-{{ user }}'"
  when: user != 'root'

- name: place gitconfig file
  template:
    src: gitconfig.j2
    dest: "/home/{{ user }}/.gitconfig"
    owner: "{{ user }}"
    group: "{{ user }}"
  when: user != 'root'

- name: place gitignore_global
  copy:
    src: gitignore_global
    dest: "/home/{{ user }}/.gitignore_global"
    owner: "{{ user }}"
    group: "{{ user }}"
  when: user != 'root'

- name: ensure github.com is a known host
  lineinfile:
    dest: "/home/{{ user }}/.ssh/known_hosts"
    owner: "{{ user }}"
    group: "{{ user }}"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
