---
- hosts: all
  connection: local
  gather_facts: false
  vars_files:
    - config.yml
    - defaults/secrets.yml

  roles:
  - role: user
    tags: ['root', 'user']
    vars:
      user: "root"
      password: "{{ root.password }}"
      ssh_key_passphrase: "{{ root.ssh_key_passphrase }}"

  - role: user
    tags: ['mccurdyc', 'user']
    vars:
      user: "mccurdyc"
      password: "{{ mccurdyc.password }}"
      shell: "/bin/bash"
      user_groups: wheel
      ssh_key_passphrase: "{{ mccurdyc.ssh_key_passphrase }}"

  - role: packages
    tags: ['root', 'packages']
    vars:
      package_manager: pacman
      packages:
      - git
      - github-cli
      - expect
      - keychain

  - role: git
    tags: ['root', 'git']
    vars:
      user: root
      github_token: "{{ git.github_token }}"

  - role: git
    tags: ['mccurdyc', 'git']
    vars:
      user: mccurdyc
      github_token: "{{ git.github_token }}"

  - role: yay
    tags: ['mccurdyc', 'yay']
    vars:
      user: mccurdyc

  # Minimal packages (for headless hosts)
  - role: packages
    tags: ['mccurdyc', 'packages', 'minimal']
    vars:
      user: mccurdyc
      package_manager: yay
      packages:
        - nvim-packer-git
        # - 1password-cli
        - ack
        - adobe-source-code-pro-fonts
        - ansible
        - bash-language-server
        - bat
        - bc
        - bcc-tools
        - binutils
        - colordiff
        - dhcpcd
        - dive
        - docker
        - dockerfile-language-server
        - docker-compose
        - exa
        - fasd
        - fd
        - file
        - fzf
        - gawk
        - gdb
        - git
        - github-cli
        - git-crypt
        - go
        - grep
        - gzip
        - htop
        - hadolint-bin
        - iw
        - jq
        - keybase
        - keychain
        - linux
        - linux-firmware
        - linux-headers
        - lldb
        - llvm
        - lsb-release
        - lsof
        - make
        - man-db
        - man-pages
        - mkcert
        - mosh
        - mtr
        - nano
        - neofetch
        - neovim
        - netctl
        # - nerd-fonts-complete
        - nerd-fonts-source-code-pro
        - netperf
        - net-tools
        - networkmanager
        - nftables
        - ngrok-bin
        - nmap
        - nodejs
        - nodejs-lua-fmt
        - nodejs-markdownlint-cli
        - npm
        - nvim-packer-git
        - openbsd-netcat
        - openssh
        - pacman
        - parted
        - python-bcc
        - python-pip
        - python-pynvim
        - qemu-headless
        - ripgrep
        - rsync
        - ruby
        - rust-analyzer
        - sed
        - shellcheck
        - shfmt
        - speedtest-cli
        - strace
        - subnetcalc
        - sudo
        - tailscale
        - tcpdump
        - terraform-ls-bin
        - terraform-lsp-bin
        - tflint-bin
        - tfswitch-bin
        - the_silver_searcher
        - tig
        - tmux
        - traceroute
        - tree
        - trivy
        - ttf-font-awesome
        - unzip
        - vim
        - wget
        - which
        - whois
        - xclip
        - yamllint
        - yaml-language-server
        - yay-bin
        - zip
        - zsh

  # Extra packages (for headless hosts)
  - role: packages
    tags: ['mccurdyc', 'packages', 'extra']
    vars:
      user: mccurdyc
      package_manager: yay
      packages:
        - firecracker-bin
        - hugo-git
        - ignite-bin
        - libvirt
        - vagrant
    when: 'config.packages.extra == true'

  # Minimal packages (for headed hosts)
  - role: packages
    tags: ['mccurdyc', 'packages', 'headed']
    vars:
      user: mccurdyc
      package_manager: yay
      packages:
        - alacritty
        - alsa-utils
        - chromium
        - code
        - feh
        - firefox
        - graphviz
        - i3blocks
        - i3-gaps
        - i3lock
        - i3status
        - imagemagick
        - light
        - mupdf
        - nemo
        - networkmanager
        - obsidian-appimage
        - pavucontrol
        - polybar-git
        - pulseaudio-bluetooth
        - python-grip
        - ranger
        - rofi
        - scrot
        - signal-desktop
        - simplescreenrecorder
        - spotify
        - vifm
        - w3m
    when: 'config.packages.headless == false'

  # Work packages
  - role: packages
    tags: ['mccurdyc', 'packages', 'work']
    vars:
      user: mccurdyc
      package_manager: yay
      packages:
        - helm
        - kubectl-bin
        - kubectx
        - osquery
        - prometheus
        - slack-desktop
        - zoom
    when: 'config.profile == "work" and config.packages.headless|bool == false'
